### ISSUE TITLE
End of the Installation fails

### ISSUE THREAD

**Issue by Goeks1** [iliarien/MpegtvInstaller#2]
I am receiving the below error in the end of the installtion.
OS: Ubuntu 18 Bionic Beaver

`	┌────────────────────────────────────────────────────────────────────────┐	
	│[R] Getting MpegTv Informations                                         │	
	└────────────────────────────────────────────────────────────────────────┘	
 
Enter Main http Port : 8080
Enter mysql username : mpegtv
Enter mysql password : XXXX
Staring Main With 8080 http port
 
Your Choice : /usr/local/bin/mpegtv: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

**Comment by Goeks1** [comment]
Fixed with:
apt --fix-broken install

**Comment by iliarien** [comment]
Please consider that it's for ubuntu 18, otherwise when we force install on debian for example it will break all the system
